export { runScan } from './engine/runner.js';
export { walkRepo } from './engine/walker.js';
export { allRules } from './rules/index.js';
export { computeScore, scoreAxis, RUBRIC_VERSION } from './score/score.js';
export { formatVerdict, toJsonReport, badgeMarkdown } from './report.js';
export { measureRuns } from './axes/runs/index.js';
export { measureHonest } from './axes/honest/index.js';
export { runInit } from './commands/init.js';
export { runProtect } from './commands/protect.js';
export { guardContent } from './guard/guard.js';
export type { GuardVerdict } from './guard/guard.js';
export type { Finding, Rule, ScanContext, ScanOptions, ScanResult } from './engine/types.js';
export type { ScoreResult, AxisScore } from './score/score.js';
export type { AxisReport, AxisEvidence, AxisStatus, Claim, ClaimReceipt } from './axes/types.js';
